LDLIBS += -lstdc++
CXXFLAGS += -O2
OBJ := BitString.o\
	DynSysModel.o \
    FileManager.o \
    GAModel.o \
    GAParams.o \
	NTuple.o \
	Polynomial.o \
	Monomial.o \
    React.o \
   

React : $(OBJ)

clean : rm -rf *.o React 

